services:

  postgres:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    container_name: ema_db_postgres
    ports:
      - 15432:5432
    restart: always
    user: root
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=p@ssw0rd
      - TZ=Asia/Tokyo
      - LANG=ja_JP.utf8
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5

  sqlserver:
    build:
      context: ./.docker/sqlserver
      dockerfile: Dockerfile
    container_name: ema_db_sqlserver
    ports:
      - 11433:1433
    restart: always
    user: root
    environment:
      - ACCEPT_EULA=Y                     # 使用許諾契約書の同意
      - TZ=Asia/Tokyo                     # タイムゾーン
      - MSSQL_COLLATION=Japanese_CI_AS    # 照合順序
      - MSSQL_LCID=1041                   # 言語
      - MSSQL_AGENT_ENABLED=true          # SQLServerAgent
      - MSSQL_SA_PASSWORD=StrongP@ssw0rd  # saユーザーのパスワード
      - MSSQL_TCP_PORT=1433               # SQLServerが使用するTCPポート番号
